### PR TITLE
add Enterprise Version and devtools option, update userAgent

### PR DESCRIPTION
**Pull request by jlokos**

### CODE REVIEW

**Comment by agam778** [comment]
No luck here...

Maybe it's because of this? https://social.technet.microsoft.com/wiki/contents/articles/53250.building-electron-application-to-interact-with-sharepoint-using-oauth-implicit-grant-flow.aspx

Also, what type of account do you have?

**Comment by agam778** [comment]
Oh, wait. That's how the Office Enterprise works. Try it on the browser.
It launches the new document in the new tab, but my electron app is forcing it to open in the new window, which does not allow it to load.

So maybe just using the new window for the enterprise account is the solution. I'll see if I can do something else.

**Comment by agam778** [comment]
I'll merge it for now, and then update some stuff 👍🏻

**Comment by jlokos** [comment]
Yes exactly - that's why I am quite confused as you said launching already made files does work just not making new files while using the same window option. Do you think there is any workaround? Thanks for merging the PR hope it was helpful.

**Pull request merged**
